# Generated by Django 4.2.6 on 2023-11-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_caste_languages_mothertongue_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermaritalstatuspreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnermaritalstatuspreference', to='users.user'),
        ),
        migrations.AlterField(
            model_name='partnerreligionpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerreligionpreference', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userpostgraduation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerpostgraduationpreference', to='users.user'),
        ),
    ]
