# Generated by Django 4.2.6 on 2023-12-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_linkedaccount_phone_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaccount',
            name='phone_is_verified',
        ),
        migrations.RemoveField(
            model_name='linkedaccount',
            name='preferred_time_connect',
        ),
    ]
