# Generated by Django 4.2.6 on 2023-12-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_linkedaccount_phone_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
