# Generated by Django 4.2.6 on 2023-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='regular_plan',
            field=models.BooleanField(default=True),
        ),
    ]
