# Generated by Django 4.2.6 on 2023-12-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notifications'),
        ('users', '0008_subscription_regular_plan'),
    ]

    operations = [
    ]
