# Generated by Django 4.2.6 on 2023-12-19 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=True)),
                ('viewed_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to='users.stories')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_viewedby', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Viewed_Stories',
            },
        ),
    ]
