# Generated by Django 4.2.6 on 2023-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bachelor_of_day',
            field=models.BooleanField(default=False, help_text='If True then user is bachelor of the day'),
        ),
    ]
