# Generated by Django 4.2.6 on 2023-12-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_bachelor_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bachelor_of_day',
        ),
        migrations.CreateModel(
            name='BachelorOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_of_the_day', to='users.user')),
            ],
        ),
    ]
