# Generated by Django 4.2.6 on 2024-01-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_is_bachelor_of_day_bacheloroftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactsviewed', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('seen_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seencontact', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactsviewed', to='users.user')),
            ],
        ),
    ]
