# Generated by Django 4.2.6 on 2024-01-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_contactviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beauty_consciousness',
            field=models.BooleanField(help_text='If true you are a conscious about beauty/body'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foodie',
            field=models.BooleanField(help_text='If true you are a foodie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manglik',
            field=models.BooleanField(help_text='If true means you state you are manglik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sibling',
            field=models.BooleanField(help_text='Indicates whether user has siblings or not'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_out',
            field=models.BooleanField(help_text='If true you are a interested in yogs/gym/workout'),
        ),
    ]
