# Generated by Django 4.2.6 on 2024-01-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_manglik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beauty_consciousness',
            field=models.BooleanField(blank=True, help_text='If true you are a conscious about beauty/body', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foodie',
            field=models.BooleanField(blank=True, help_text='If true you are a foodie', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manglik',
            field=models.BooleanField(blank=True, help_text='If true means you state you are manglik', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_out',
            field=models.BooleanField(blank=True, help_text='If true you are a interested in yogs/gym/workout', null=True),
        ),
    ]
