# Generated by Django 4.2.6 on 2024-01-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_successstory'),
        ('users', '0021_alter_user_sibling'),
    ]

    operations = [
    ]
