# Generated by Django 4.2.6 on 2024-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_nts_beauty_consciousness_user_nts_foodie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nts_beauty_consciousness',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nts_foodie',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nts_manglik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nts_sibling',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nts_work_out',
        ),
        migrations.AlterField(
            model_name='user',
            name='beauty_consciousness',
            field=models.IntegerField(blank=True, default=-1, help_text='If true you are a conscious about beauty/body', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foodie',
            field=models.IntegerField(blank=True, default=-1, help_text='If true you are a foodie', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manglik',
            field=models.IntegerField(blank=True, default=-1, help_text='If true means you state you are manglik', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sibling',
            field=models.IntegerField(blank=True, default=-1, help_text='Indicates whether user has siblings or not', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_out',
            field=models.IntegerField(blank=True, default=-1, help_text='If true you are a interested in yogs/gym/workout', null=True),
        ),
    ]
