# Generated by Django 4.2.6 on 2024-01-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_user_nts_beauty_consciousness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='partner_mlp_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='partner_mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='partner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
