# Generated by Django 4.2.6 on 2024-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_successstory_partner_mlp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video',
            field=models.TextField(default='[]'),
        ),
    ]
