# Generated by Django 4.2.6 on 2024-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_upgrade_subscription',
            field=models.IntegerField(default=-1, help_text='This indicates if user can upgrade their current subscription or not, -1 for no subcription, 1 for can upgrade and 0 for not able to upgrade'),
        ),
    ]
