# Generated by Django 4.2.6 on 2024-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_can_upgrade_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='video',
            field=models.TextField(default='[]'),
        ),
    ]
