# Generated by Django 4.2.6 on 2024-01-17 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_successstory_image_successstory_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='expertise',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='graduation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='mlp_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='user_post_graduation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
