# Generated by Django 4.2.6 on 2024-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_ratingreview_created_date_ratingreview_expertise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingreview',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='profile_pictures',
            field=models.TextField(default='[]'),
        ),
    ]
