# Generated by Django 4.2.6 on 2024-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_ratingreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacheloroftheday',
            name='religion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
