# Generated by Django 4.2.6 on 2024-01-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_partner_age_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='[]', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Report Users',
            },
        ),
    ]
