# Generated by Django 4.2.6 on 2024-01-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(choices=[('all', 'ALL'), ('silverregular', 'SILVER_REGULAR'), ('goldregular', 'GOLD_REGULAR'), ('platinumregular', 'PLATINUM_REGULAR'), ('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM'), ('premium', 'PREMIUM'), ('Noplans', 'NOPLANS')], max_length=80)),
                ('message_title', models.CharField(blank=True, max_length=100, null=True)),
                ('message_body', models.CharField(blank=True, max_length=500, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Promotions and Offers',
            },
        ),
    ]
