# Generated by Django 4.2.6 on 2024-01-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_promotions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
