# Generated by Django 4.2.6 on 2024-01-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_profileview_options_profileview_visited_at'),
        ('users', '0039_delete_promotions'),
    ]

    operations = [
    ]
