# Generated by Django 4.2.6 on 2024-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_merge_20240129_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_mothertongue_preference',
            field=models.BooleanField(default=False, help_text='If False then no partner mother tongue preference'),
        ),
    ]
