# Generated by Django 4.2.6 on 2024-02-01 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_partner_mothertongue_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
