# Generated by Django 4.2.6 on 2024-02-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_successstory_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingreview',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='mlp_id',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='profile_pictures',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='user_post_graduation',
        ),
    ]
