# Generated by Django 4.2.6 on 2024-02-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_post_grad',
            field=models.BooleanField(default=True, help_text='if False then no postgraduation done by user'),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.graduation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mlp_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
