# Generated by Django 4.2.6 on 2024-02-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_completed_post_grad_user_graduation_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEndPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userblockedendpoints', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
