# Generated by Django 4.2.6 on 2024-02-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcaste',
            name='caste',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caste', to='users.caste'),
        ),
    ]
