# Generated by Django 4.2.6 on 2024-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_subcaste_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
