# Generated by Django 4.2.6 on 2024-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_user_blood_group_alter_user_body_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mlp_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
