# Generated by Django 4.2.6 on 2024-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_user_blood_group_alter_user_body_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Your Bloodgroup', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_build',
            field=models.CharField(blank=True, help_text='Indicates lean, wellbuild or heavy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_clock',
            field=models.CharField(blank=True, help_text='Indicates whether you are a morning/latenight person', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='caste',
            field=models.CharField(blank=True, help_text='Your Caste', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City you live in', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_parents',
            field=models.CharField(blank=True, help_text='City where parents reside', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='complexion',
            field=models.CharField(blank=True, help_text='Indicates Complexion', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Country you live in', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eyesight',
            field=models.CharField(blank=True, help_text='Indicates your eyesight', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_car',
            field=models.CharField(blank=True, help_text='Family owns a car', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_financial_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_house',
            field=models.CharField(blank=True, help_text='Whether house is owned or rented', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_status',
            field=models.CharField(blank=True, help_text='Your graduation status', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='horoscope_matching',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_music',
            field=models.CharField(blank=True, help_text='Indicates whether an art lover/music enthusiast', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_party',
            field=models.CharField(blank=True, help_text='Indicates whether candidate loves dining or partying', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kids_choice',
            field=models.CharField(blank=True, help_text='Indicates your preference on kids', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='nature',
            field=models.CharField(blank=True, help_text='Indicates your nature', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_car',
            field=models.CharField(blank=True, help_text='Candidate owns a car', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_physicalstatus',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_status',
            field=models.CharField(blank=True, help_text='Indicates normal or disabled', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_graduation_status',
            field=models.CharField(blank=True, help_text='Your graduation status', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_time_connect',
            field=models.CharField(blank=True, help_text='Indicates preferred time for connect', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_createdby',
            field=models.CharField(blank=True, default='Candidate', help_text='Indicates who has created that profile', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Indicates your doctor's registartion number", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religious_practices',
            field=models.CharField(blank=True, help_text='Indicates religious practice of candidates', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, help_text='Indicates whether residence is owned or rented', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='schooling_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State you live in', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
