# Generated by Django 4.2.6 on 2024-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_subscription_name_alter_user_birth_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacheloroftheday',
            name='religion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='partner_mlp_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
