# Generated by Django 4.2.6 on 2024-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_bacheloroftheday_religion_alter_caste_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='partner_mlp_id',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mlp_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
