# Generated by Django 4.2.6 on 2024-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_successstory_partner_mlp_id_alter_user_mlp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='beauty_consciousness',
            field=models.IntegerField(blank=True, db_index=True, default=-1, help_text='If true you are a conscious about beauty/body', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_location',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, db_index=True, help_text='Your Bloodgroup', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_build',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates lean, wellbuild or heavy', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_clock',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates whether you are a morning/latenight person', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_upgrade_subscription',
            field=models.IntegerField(db_index=True, default=-1, help_text='This indicates if user can upgrade their current subscription or not, -1 for no subcription, 1 for can upgrade and 0 for not able to upgrade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='caste',
            field=models.CharField(blank=True, db_index=True, help_text='Your Caste', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='City you live in', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_parents',
            field=models.CharField(blank=True, db_index=True, help_text='City where parents reside', max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_post_grad',
            field=models.BooleanField(db_index=True, default=True, help_text='if False then no postgraduation done by user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='complexion',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates Complexion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Country you live in', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='disease_history',
            field=models.CharField(blank=True, db_index=True, help_text='Disease/Surgery undergone', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='drinking_habits',
            field=models.CharField(blank=True, choices=[('nd', 'Non-Drinker'), ('sd', 'Social Drinker'), ('od', 'Occasional Drinker'), ('rd', 'Regular Drinker')], db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eating_habits',
            field=models.CharField(blank=True, choices=[('veg', 'VEGETARIAN'), ('non_veg', 'NON-VEGETARIAN'), ('eggitarian', 'VEG+EGG'), ('jain', 'JAIN')], db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='eyesight',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates your eyesight', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_profile',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_car',
            field=models.CharField(blank=True, db_index=True, help_text='Family owns a car', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_environment',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_financial_status',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_house',
            field=models.CharField(blank=True, db_index=True, help_text='Whether house is owned or rented', max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_photos',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_education',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_occupation',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foodie',
            field=models.IntegerField(blank=True, db_index=True, default=-1, help_text='If true you are a foodie', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='future_aspirations',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_institute',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_status',
            field=models.CharField(blank=True, db_index=True, help_text='Your graduation status', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='horoscope_matching',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_profile',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_music',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates whether an art lover/music enthusiast', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_party',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates whether candidate loves dining or partying', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_primary_account',
            field=models.BooleanField(db_index=True, default=True, help_text='if false then this account is linked to someone else'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kids_choice',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates your preference on kids', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='language_spoken', to='users.languages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_profile',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandatory_questions_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='If True then it means user have completed its mandatory questions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manglik',
            field=models.IntegerField(blank=True, db_index=True, default=-1, help_text='If true means you state you are manglik', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_education',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_occupation',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_tongue',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='mother_tongue', to='users.mothertongue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='nature',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates your nature', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_hobbies',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_car',
            field=models.CharField(blank=True, db_index=True, help_text='Candidate owns a car', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_age_from',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_age_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner age preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_age_to',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_caste_from',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_caste_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner caste preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_cities_from',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_cities_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner cities preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_country_from',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_country_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner country preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_expertise_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner expertise preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_graduation_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no graduation preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_height_from',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_height_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner height preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_height_to',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_income_from',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_income_to',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_marital_status_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner marital status preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_mothertongue_from',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='partner_mothertongue', to='users.mothertongue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_mothertongue_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner mother tongue preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_physicalstatus',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_postgraduation_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no postgrad preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_religion_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner religion preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_specialization_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no specialization preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_state_from',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_state_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner state preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_status',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates normal or disabled', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_graduation_institute',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_graduation_status',
            field=models.CharField(blank=True, db_index=True, help_text='Your graduation status', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_time_connect',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates preferred time for connect', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession_description',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_createdby',
            field=models.CharField(blank=True, db_index=True, default='Candidate', help_text='Indicates who has created that profile', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pictures',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, help_text="Indicates your doctor's registartion number", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religious_practices',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates religious practice of candidates', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, db_index=True, help_text='Indicates whether residence is owned or rented', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='schooling_details',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sibling',
            field=models.IntegerField(blank=True, db_index=True, default=-1, help_text='Indicates whether user has siblings or not', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoking_habits',
            field=models.CharField(blank=True, choices=[('ns', 'Non-Smoker'), ('os', 'Occasional Smoker'), ('rs', 'Regular Smoker'), ('tq', 'Trying to Quit')], db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='State you live in', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_birth',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.TextField(db_index=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_out',
            field=models.IntegerField(blank=True, db_index=True, default=-1, help_text='If true you are a interested in yogs/gym/workout', null=True),
        ),
    ]
