# Generated by Django 4.2.6 on 2024-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_user_about_alter_user_activity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_photos',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='future_aspirations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_hobbies',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_caste_from',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_cities_from',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_country_from',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_physicalstatus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_state_from',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pictures',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.TextField(default='[]'),
        ),
    ]
