# Generated by Django 4.2.6 on 2024-03-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_bacheloroftheday_religion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='future_aspirations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
