# Generated by Django 4.2.6 on 2024-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_user_about_alter_user_future_aspirations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
