# Generated by Django 4.2.6 on 2024-03-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_notifications_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_income_preference',
            field=models.BooleanField(db_index=True, default=False, help_text='If False then no partner income preference'),
        ),
    ]
