# Generated by Django 4.2.6 on 2024-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_user_partner_income_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcaste',
            name='name',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
