# Generated by Django 4.2.6 on 2024-04-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_subcaste_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='is_subscription_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
