# Generated by Django 4.2.6 on 2024-04-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_usersubscription_is_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnergraduationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnergraduationpreference', to='users.user'),
        ),
        migrations.AlterField(
            model_name='partnerpgpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerpgpreference', to='users.user'),
        ),
    ]
