# Generated by Django 4.2.6 on 2024-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_alter_partnergraduationpreference_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlp_id', models.CharField(db_index=True, max_length=50)),
                ('reason', models.CharField(db_index=True, max_length=180, null=True)),
                ('experience', models.CharField(db_index=True, max_length=180, null=True)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='successstory',
            name='experience',
            field=models.CharField(db_index=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='reason',
            field=models.CharField(db_index=True, max_length=180, null=True),
        ),
    ]
