# Generated by Django 4.2.6 on 2024-05-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_applesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_ios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.applesubscription'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
