# Generated by Django 4.2.6 on 2023-12-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscription_regular_plan'),
        ('transactions', '0002_transactionentity_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentity',
            name='coupon_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='transactions.coupon'),
        ),
        migrations.AlterField(
            model_name='transactionentity',
            name='subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.subscription'),
        ),
        migrations.AlterField(
            model_name='transactionentity',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
    ]
