# Generated by Django 4.2.6 on 2023-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactionentity_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentity',
            name='mihpayid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
