# Generated by Django 4.2.6 on 2024-02-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_blockendpoints'),
        ('transactions', '0004_alter_transactionentity_mihpayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
