# Generated by Django 4.2.6 on 2024-05-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_applesubscription'),
        ('transactions', '0006_appletransactionentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appletransactionentity',
            name='subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.applesubscription'),
        ),
    ]
