# Generated by Django 4.2.6 on 2024-05-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_applesubscription'),
        ('transactions', '0007_alter_appletransactionentity_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appletransactionentity',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='userapplesubscription', to='users.user'),
        ),
    ]
