# Generated by Django 4.2.6 on 2024-06-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_usersubscription_subscription_ios_and_more'),
        ('transactions', '0008_alter_appletransactionentity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('trnsId', models.CharField(max_length=255, null=True)),
                ('couponCode', models.CharField(max_length=50, null=True)),
                ('countryCode', models.CharField(max_length=10, null=True)),
                ('subscriptionId', models.CharField(max_length=255, null=True)),
                ('merchantKey', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='webapptransaction', to='users.user')),
            ],
        ),
    ]
