# Generated by Django 4.2.6 on 2024-02-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_partner_mothertongue_preference'),
        ('notification_settings', '0002_alter_notificationsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.user'),
        ),
    ]
