# Generated by Django 4.2.6 on 2023-11-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_caste_languages_mothertongue_specialization_and_more'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchresult', to='users.user'),
        ),
    ]
