# Generated by Django 4.2.6 on 2023-12-04 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_searchresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
