# Generated by Django 4.2.6 on 2023-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_searchresult_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
