# Generated by Django 4.2.6 on 2023-12-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_usersubscription'),
        ('search', '0004_alter_searchresult_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_caste', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_to', models.IntegerField(blank=True, null=True)),
                ('height_from', models.IntegerField(blank=True, null=True)),
                ('height_to', models.IntegerField(blank=True, null=True)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('weight_from', models.IntegerField(blank=True, null=True)),
                ('weight_to', models.IntegerField(blank=True, null=True)),
                ('family_financial_status', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('drinking_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('eating_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
