# Generated by Django 4.2.6 on 2023-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_usersearchpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearchpreferences',
            old_name='hobbies',
            new_name='expertise',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='drinking_habits',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='eating_habits',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='family_financial_status',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='height_from',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='height_to',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='smoking_habits',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='weight_from',
        ),
        migrations.RemoveField(
            model_name='usersearchpreferences',
            name='weight_to',
        ),
        migrations.AddField(
            model_name='usersearchpreferences',
            name='graduation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersearchpreferences',
            name='post_graduation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersearchpreferences',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersearchpreferences',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
