# Generated by Django 4.2.6 on 2024-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_usersearchpreferences_filter_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchpreferences',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
